pipeline:
  identifier: Build_willemjanvanasseldonk_java_maven_junit_helloworld_1706779300030
  name: Build java-maven-junit-helloworld
  orgIdentifier: default
  projectIdentifier: Hello_World
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706090911781
        repoName: willemjanvanasseldonk/java-maven-junit-helloworld
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
